name: Airflow Dags SYNC

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'

jobs:
  enter_private_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH directory
        run: |
          mkdir -p $HOME/.ssh
  
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SH_SSH_PRIVATE_KEY }}" > $HOME/.ssh/airflow-key.pem
          chmod 600 $HOME/.ssh/airflow-key.pem
  
      - name: SSH to private EC2
        run: |
          # 호스트 키 추가
          ssh-keyscan -H 52.78.71.211 >> $HOME/.ssh/known_hosts
  
          # SSH 연결
          ssh -i $HOME/.ssh/airflow-key.pem ubuntu@52.78.71.211
          echo "Success"

