name: Airflow Dags SYNC

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'

jobs:
  sync_scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETE_ACCESS_KEY }}
          aws-region: ap-northeast-2  # AWS S3 Bucket이 있는 리전으로 교체

      - name: Sync Dags to AWS S3
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            ./dags s3://de-4-1-bucket/airflow/dags \
            --delete
            echo "S3 Sync complete!"
  enter_private_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Enter private EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/de-4-1-key.pem
          chmod 600 $HOME/de-4-1-key.pem
  
          # 호스트 키 추가
          ssh-keyscan -H ec2-43-203-182-0.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts
  
          # SSH 연결
          ssh -i $HOME/de-4-1-key.pem ubuntu@ec2-43-203-182-0.ap-northeast-2.compute.amazonaws.com
          echoi "Success"
          #ssh -i $HOME/de-4-1-key.pem -o ProxyJump=ubuntu@ec2-43-203-182-0.ap-northeast-2.compute.amazonaws.com ubuntu@10.0.139.241 'ls /home'


  # enter_private_ec2_airflow:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Enter private EC2 - airflow
  #       run: |
  #         echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/de-4-1-key.pem
  #         chmod 600 $HOME/de-4-1-key.pem
  #         ssh -i $HOME/de-4-1-key.pem ec2-user@10.0.139.241 "sudo su - airflow -c 'ls /var/lib/airflow/dags'"
  #         echo "Success2"
      # - name: Enter private EC2
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/de-4-1-key.pem
      #     ssh -i $HOME/de-4-1-key.pem ec2-user@10.0.139.241 'ls /home'
      #     echo "Success"
      # - name: Enter private EC2- airflow
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/de-4-1-key.pem
      #     ssh -i $HOME/de-4-1-key.pem ec2-user@10.0.139.241 "sudo su - airflow -c 'ls /var/lib/airflow/dags'"
      #     echo "Success2"
      
      # - name: Sync AWS S3 to Airflow_prod
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/de-4-1-key.pem
      #     chmod 600 $HOME/de-4-1-key.pem
      #     ssh -i $HOME/de-4-1-key.pem ec2-user@10.0.139.241 "sudo su - airflow -c 'aws s3 sync --region ap-northeast-2 s3://de-4-1-bucket/airflow/dags /var/lib/airflow/dags --delete'"
      #     echo "Airflow prod server Sync complete!"
      # env:
      #   SSH_PRIVATE_KEY: $HOME/.ssh/de-4-1-key.pem

