name: Airflow Dags SYNC

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'

jobs:
  sync_scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETE_ACCESS_KEY }}
          aws-region: ap-northeast-2  # AWS S3 Bucket이 있는 리전으로 교체


      - name: Sync Dags to AWS S3
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            ./dags s3://de-4-1-bucket/airflow/dags \
            --delete
            echo "S3 Sync complete!"

      - name: Sync AWS S3 to Airflow_prod
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
          s3://de-4-1-bucket/airflow/dags \
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@$10.0.139.241 "sudo su - airflow -c 'aws s3 sync --region ap-northeast-2 s3://de-4-1-bucket/airflow/dags /var/lib/airflow/dags --delete'"
          echo "Airflow prod server Sync complete!"
        env:
          SSH_PRIVATE_KEY: ~/.ssh/de-4-1-key.pem

