name: Airflow Dags SYNC

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'

jobs:
  sync_scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SH_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SH_AWS_SECRETE_ACCESS_KEY }}
          aws-region: ap-northeast-2  # AWS S3 Bucket이 있는 리전으로 교체

      - name: Sync Dags to AWS S3
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            ./dags s3://de-4-1-bucket/airflow/dags \
            --delete
            echo "S3 Sync complete!"
  enter_private_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
      - name: Enter private EC2
        run: |
          echo "${{ secrets.SH_SSH_PRIVATE_KEY }}" > $HOME/airflow-key.pem
          chmod 600 $HOME/airflow-key.pem
  
          # # 호스트 키 추가
          # ssh-keyscan -H 52.78.71.211 >> ~/.ssh/known_hosts
  
          # SSH 연결
          ssh -i $HOME/airflow-key.pem ubuntu@52.78.71.211
          echo "Success"
          # ssh -i $HOME/airflow-key.pem -o ProxyJump=ubuntu@52.78.71.211 ubuntu@10.0.139.50 'ls /home'
          # echo "Success2"

